import ExcelSheet from "@/component/ExcelSheet";
import React from "react";

const ExcelSheetPage = async () => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts`);
  const data = await res.json();

  console.log("data", data);

  const empAttendanceData = [
    {
      EmpCode: 55488,
      Name: "Md. Robiul Hasan",
      ShiftDate: "01/02/2024",
      Day: "THURSDAY",
      Shift: "9AM-6PM",
      SSLStatus: "Present",
      Status: "Present",
      RevisedStatus: "Present",
      IN: "8:59:00 a",
      OUT: "18:01:13 a",
      WorkTime: "09:02:13",
      ActualOTDone: "0 h 0 min",
      OTRequest: 0,
      Remarks: "1: According to CCTV",
    },
    {
      EmpCode: 55488,
      Name: "Md. Robiul Hasan",
      ShiftDate: "01/02/2024",
      Day: "THURSDAY",
      Shift: "9AM-6PM",
      SSLStatus: "Present",
      Status: "Present",
      RevisedStatus: "Present",
      IN: "8:59:00 a",
      OUT: "18:01:13 a",
      WorkTime: "09:02:13",
      ActualOTDone: "0 h 0 min",
      OTRequest: 0,
      Remarks: "1: According to CCTV",
    },
    {
      EmpCode: 55488,
      Name: "Md. Robiul Hasan",
      ShiftDate: "01/02/2024",
      Day: "THURSDAY",
      Shift: "9AM-6PM",
      SSLStatus: "Present",
      Status: "Present",
      RevisedStatus: "Present",
      IN: "8:59:00 a",
      OUT: "18:01:13 a",
      WorkTime: "09:02:13",
      ActualOTDone: "0 h 0 min",
      OTRequest: 0,
      Remarks: "1: According to CCTV",
    },
    {
      EmpCode: 55488,
      Name: "Md. Robiul Hasan",
      ShiftDate: "01/02/2024",
      Day: "THURSDAY",
      Shift: "9AM-6PM",
      SSLStatus: "Present",
      Status: "Present",
      RevisedStatus: "Present",
      IN: "8:59:00 a",
      OUT: "18:01:13 a",
      WorkTime: "09:02:13",
      ActualOTDone: "0 h 0 min",
      OTRequest: 0,
      Remarks: "1: According to CCTV",
    },
    {
      EmpCode: 55488,
      Name: "Md. Robiul Hasan",
      ShiftDate: "01/02/2024",
      Day: "THURSDAY",
      Shift: "9AM-6PM",
      SSLStatus: "Present",
      Status: "Present",
      RevisedStatus: "Present",
      IN: "8:59:00 a",
      OUT: "18:01:13 a",
      WorkTime: "09:02:13",
      ActualOTDone: "0 h 0 min",
      OTRequest: 0,
      Remarks: "1: According to CCTV",
    },
    {
      EmpCode: 55488,
      Name: "Md. Robiul Hasan",
      ShiftDate: "01/02/2024",
      Day: "THURSDAY",
      Shift: "9AM-6PM",
      SSLStatus: "Present",
      Status: "Present",
      RevisedStatus: "Present",
      IN: "8:59:00 a",
      OUT: "18:01:13 a",
      WorkTime: "09:02:13",
      ActualOTDone: "0 h 0 min",
      OTRequest: 0,
      Remarks: "1: According to CCTV",
    },
    {
      EmpCode: 55488,
      Name: "Md. Robiul Hasan",
      ShiftDate: "01/02/2024",
      Day: "THURSDAY",
      Shift: "9AM-6PM",
      SSLStatus: "Present",
      Status: "Present",
      RevisedStatus: "Present",
      IN: "8:59:00 a",
      OUT: "18:01:13 a",
      WorkTime: "09:02:13",
      ActualOTDone: "0 h 0 min",
      OTRequest: 0,
      Remarks: "1: According to CCTV",
    },
    {
      EmpCode: 55488,
      Name: "Md. Robiul Hasan",
      ShiftDate: "01/02/2024",
      Day: "THURSDAY",
      Shift: "9AM-6PM",
      SSLStatus: "Present",
      Status: "Present",
      RevisedStatus: "Present",
      IN: "8:59:00 a",
      OUT: "18:01:13 a",
      WorkTime: "09:02:13",
      ActualOTDone: "0 h 0 min",
      OTRequest: 0,
      Remarks: "1: According to CCTV",
    },
    {
      EmpCode: 55488,
      Name: "Md. Robiul Hasan",
      ShiftDate: "01/02/2024",
      Day: "THURSDAY",
      Shift: "9AM-6PM",
      SSLStatus: "Present",
      Status: "Present",
      RevisedStatus: "Present",
      IN: "8:59:00 a",
      OUT: "18:01:13 a",
      WorkTime: "09:02:13",
      ActualOTDone: "0 h 0 min",
      OTRequest: 0,
      Remarks: "1: According to CCTV",
    },
    {
      EmpCode: 55488,
      Name: "Md. Robiul Hasan",
      ShiftDate: "01/02/2024",
      Day: "THURSDAY",
      Shift: "9AM-6PM",
      SSLStatus: "Present",
      Status: "Present",
      RevisedStatus: "Present",
      IN: "8:59:00 a",
      OUT: "18:01:13 a",
      WorkTime: "09:02:13",
      ActualOTDone: "0 h 0 min",
      OTRequest: 0,
      Remarks: "1: According to CCTV",
    },
    {
      EmpCode: 55488,
      Name: "Md. Robiul Hasan",
      ShiftDate: "01/02/2024",
      Day: "THURSDAY",
      Shift: "9AM-6PM",
      SSLStatus: "Present",
      Status: "Present",
      RevisedStatus: "Present",
      IN: "8:59:00 a",
      OUT: "18:01:13 a",
      WorkTime: "09:02:13",
      ActualOTDone: "0 h 0 min",
      OTRequest: 0,
      Remarks: "1: According to CCTV",
    },
    {
      EmpCode: 55488,
      Name: "Md. Robiul Hasan",
      ShiftDate: "01/02/2024",
      Day: "THURSDAY",
      Shift: "9AM-6PM",
      SSLStatus: "Present",
      Status: "Present",
      RevisedStatus: "Present",
      IN: "8:59:00 a",
      OUT: "18:01:13 a",
      WorkTime: "09:02:13",
      ActualOTDone: "0 h 0 min",
      OTRequest: 0,
      Remarks: "1: According to CCTV",
    },
    {
      EmpCode: 55488,
      Name: "Md. Robiul Hasan",
      ShiftDate: "01/02/2024",
      Day: "THURSDAY",
      Shift: "9AM-6PM",
      SSLStatus: "Present",
      Status: "Present",
      RevisedStatus: "Present",
      IN: "8:59:00 a",
      OUT: "18:01:13 a",
      WorkTime: "09:02:13",
      ActualOTDone: "0 h 0 min",
      OTRequest: 0,
      Remarks: "1: According to CCTV",
    },
    {
      EmpCode: 55488,
      Name: "Md. Robiul Hasan",
      ShiftDate: "01/02/2024",
      Day: "THURSDAY",
      Shift: "9AM-6PM",
      SSLStatus: "Present",
      Status: "Present",
      RevisedStatus: "Present",
      IN: "8:59:00 a",
      OUT: "18:01:13 a",
      WorkTime: "09:02:13",
      ActualOTDone: "0 h 0 min",
      OTRequest: 0,
      Remarks: "1: According to CCTV",
    },
    {
      EmpCode: 55488,
      Name: "Md. Robiul Hasan",
      ShiftDate: "01/02/2024",
      Day: "THURSDAY",
      Shift: "9AM-6PM",
      SSLStatus: "Present",
      Status: "Present",
      RevisedStatus: "Present",
      IN: "8:59:00 a",
      OUT: "18:01:13 a",
      WorkTime: "09:02:13",
      ActualOTDone: "0 h 0 min",
      OTRequest: 0,
      Remarks: "1: According to CCTV",
    },
  ];

  return (
    <div>
      <ExcelSheet empAttendanceData={empAttendanceData} />
    </div>
  );
};

export default ExcelSheetPage;
