import DownloadExcel from "@/component/ExcelSheet";
import React from "react";

const ExcelSheetPage = async () => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts`);
  const data = await res.json();

  const jsonData = [
    {
      "Emp Code": 101,
      Name: "John Doe",
      "Shift Date": "2024-07-01",
      Day: "Monday",
      Shift: "Morning",
      "SSL Status": "Active",
      Status: "Present",
      "Revised Status": "Confirmed",
      IN: "09:00 AM",
      OUT: "05:00 PM",
      "Work Time (including interval)": "8 hours",
      "Actual OT Done": "0 hours",
      "OT Request": "None",
      Remarks: "N/A",
    },
    {
      "Emp Code": 102,
      Name: "Jane Smith",
      "Shift Date": "2024-07-01",
      Day: "Monday",
      Shift: "Morning",
      "SSL Status": "Active",
      Status: "Absent",
      "Revised Status": "N/A",
      IN: "N/A",
      OUT: "N/A",
      "Work Time (including interval)": "0 hours",
      "Actual OT Done": "0 hours",
      "OT Request": "N/A",
      Remarks: "Sick leave",
    },
    {
      "Emp Code": 103,
      Name: "Alice Johnson",
      "Shift Date": "2024-07-01",
      Day: "Monday",
      Shift: "Evening",
      "SSL Status": "Active",
      Status: "Present",
      "Revised Status": "Confirmed",
      IN: "01:00 PM",
      OUT: "09:00 PM",
      "Work Time (including interval)": "8 hours",
      "Actual OT Done": "1 hour",
      "OT Request": "Approved",
      Remarks: "Completed extra task",
    },
    {
      "Emp Code": 104,
      Name: "Bob Brown",
      "Shift Date": "2024-07-01",
      Day: "Monday",
      Shift: "Morning",
      "SSL Status": "Active",
      Status: "Present",
      "Revised Status": "Confirmed",
      IN: "09:00 AM",
      OUT: "05:00 PM",
      "Work Time (including interval)": "8 hours",
      "Actual OT Done": "0 hours",
      "OT Request": "None",
      Remarks: "N/A",
    },
    {
      "Emp Code": 105,
      Name: "Charlie Davis",
      "Shift Date": "2024-07-01",
      Day: "Monday",
      Shift: "Night",
      "SSL Status": "Active",
      Status: "Absent",
      "Revised Status": "N/A",
      IN: "N/A",
      OUT: "N/A",
      "Work Time (including interval)": "0 hours",
      "Actual OT Done": "0 hours",
      "OT Request": "N/A",
      Remarks: "Family emergency",
    },
    {
      "Emp Code": 104,
      Name: "Bob Brown",
      "Shift Date": "2024-07-01",
      Day: "Monday",
      Shift: "Morning",
      "SSL Status": "Active",
      Status: "Present",
      "Revised Status": "Confirmed",
      IN: "09:00 AM",
      OUT: "05:00 PM",
      "Work Time (including interval)": "8 hours",
      "Actual OT Done": "0 hours",
      "OT Request": "None",
      Remarks: "N/A",
    },
    {
      "Emp Code": 105,
      Name: "Charlie Davis",
      "Shift Date": "2024-07-01",
      Day: "Monday",
      Shift: "Night",
      "SSL Status": "Active",
      Status: "Absent",
      "Revised Status": "N/A",
      IN: "N/A",
      OUT: "N/A",
      "Work Time (including interval)": "0 hours",
      "Actual OT Done": "0 hours",
      "OT Request": "N/A",
      Remarks: "Family emergency",
    },
    {
      "Emp Code": 104,
      Name: "Bob Brown",
      "Shift Date": "2024-07-01",
      Day: "Monday",
      Shift: "Morning",
      "SSL Status": "Active",
      Status: "Present",
      "Revised Status": "Confirmed",
      IN: "09:00 AM",
      OUT: "05:00 PM",
      "Work Time (including interval)": "8 hours",
      "Actual OT Done": "0 hours",
      "OT Request": "None",
      Remarks: "N/A",
    },
    {
      "Emp Code": 105,
      Name: "Charlie Davis",
      "Shift Date": "2024-07-01",
      Day: "Monday",
      Shift: "Night",
      "SSL Status": "Active",
      Status: "Absent",
      "Revised Status": "N/A",
      IN: "N/A",
      OUT: "N/A",
      "Work Time (including interval)": "0 hours",
      "Actual OT Done": "0 hours",
      "OT Request": "N/A",
      Remarks: "Family emergency",
    },
    {
      "Emp Code": 104,
      Name: "Bob Brown",
      "Shift Date": "2024-07-01",
      Day: "Monday",
      Shift: "Morning",
      "SSL Status": "Active",
      Status: "Present",
      "Revised Status": "Confirmed",
      IN: "09:00 AM",
      OUT: "05:00 PM",
      "Work Time (including interval)": "8 hours",
      "Actual OT Done": "0 hours",
      "OT Request": "None",
      Remarks: "N/A",
    },
    {
      "Emp Code": 105,
      Name: "Charlie Davis",
      "Shift Date": "2024-07-01",
      Day: "Monday",
      Shift: "Night",
      "SSL Status": "Active",
      Status: "Absent",
      "Revised Status": "N/A",
      IN: "N/A",
      OUT: "N/A",
      "Work Time (including interval)": "0 hours",
      "Actual OT Done": "0 hours",
      "OT Request": "N/A",
      Remarks: "Family emergency",
    },
    {
      "Emp Code": 104,
      Name: "Bob Brown",
      "Shift Date": "2024-07-01",
      Day: "Monday",
      Shift: "Morning",
      "SSL Status": "Active",
      Status: "Present",
      "Revised Status": "Confirmed",
      IN: "09:00 AM",
      OUT: "05:00 PM",
      "Work Time (including interval)": "8 hours",
      "Actual OT Done": "0 hours",
      "OT Request": "None",
      Remarks: "N/A",
    },
    {
      "Emp Code": 105,
      Name: "Charlie Davis",
      "Shift Date": "2024-07-01",
      Day: "Monday",
      Shift: "Night",
      "SSL Status": "Active",
      Status: "Absent",
      "Revised Status": "N/A",
      IN: "N/A",
      OUT: "N/A",
      "Work Time (including interval)": "0 hours",
      "Actual OT Done": "0 hours",
      "OT Request": "N/A",
      Remarks: "Family emergency",
    },
    {
      "Emp Code": 104,
      Name: "Bob Brown",
      "Shift Date": "2024-07-01",
      Day: "Monday",
      Shift: "Morning",
      "SSL Status": "Active",
      Status: "Present",
      "Revised Status": "Confirmed",
      IN: "09:00 AM",
      OUT: "05:00 PM",
      "Work Time (including interval)": "8 hours",
      "Actual OT Done": "0 hours",
      "OT Request": "None",
      Remarks: "N/A",
    },
    {
      "Emp Code": 105,
      Name: "Charlie Davis",
      "Shift Date": "2024-07-01",
      Day: "Monday",
      Shift: "Night",
      "SSL Status": "Active",
      Status: "Absent",
      "Revised Status": "N/A",
      IN: "N/A",
      OUT: "N/A",
      "Work Time (including interval)": "0 hours",
      "Actual OT Done": "0 hours",
      "OT Request": "N/A",
      Remarks: "Family emergency",
    },
  ];
  return (
    <div>
      <DownloadExcel
        data={jsonData}
        title="Walton Digi-Tech Industries Ltd."
        subtitle1="Location: Corporate Office (Computer)"
        subtitle2="Employee Attendance Report"
      />
    </div>
  );
};

export default ExcelSheetPage;
