import ResponsiveAppBar from "@/component/ResponsiveAppBar";
import AuthProvider from "./auth/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ResponsiveAppBar />
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
